source 'https://supermarket.chef.io'

cookbook 'runit'
cookbook 'application'
cookbook 'application_nginx', git: 'https://github.com/poise/application_nginx.git'
cookbook 'application_ruby', '= 3.0.2'
cookbook 'build-essential'
cookbook 'chef-client'
cookbook 'database'
cookbook 'hostname'
cookbook 'iptables'
cookbook 'logrotate'
cookbook 'nginx'
cookbook 'ntp'
cookbook 'postfix'
cookbook 'postgresql'
cookbook "rbenv", github: "corewebdesign/chef-rbenv"
cookbook 'redisio'
cookbook 'resque'
cookbook 'ruby_build'
cookbook 'ssh_known_hosts'
cookbook 'sudo'
cookbook 'users', '= 1.7.0'
cookbook 'sshd'
cookbook 'nodejs'
cookbook 'libmysqlclient', '~> 0.1.0'
cookbook 'mysql2_chef_gem'
cookbook 'mysql'
