source 'https://supermarket.chef.io'

cookbook 'build-essential'
cookbook 'iptables'
cookbook 'rbenv'
cookbook 'ruby_build'
cookbook 'application'
cookbook 'application_ruby'
cookbook 'application_nginx', git: 'https://github.com/poise/application_nginx.git'
cookbook 'chef-client'
cookbook 'nginx'
cookbook 'logrotate'
cookbook 'ssh_known_hosts'
cookbook 'database'
cookbook 'ntp'
cookbook 'postgresql'
