source 'https://supermarket.chef.io'

cookbook 'build-essential'
cookbook 'iptables'
cookbook 'rbenv'
cookbook 'application'
cookbook 'application_ruby'
cookbook 'application_nginx'
cookbook 'chef-client'
cookbook 'nginx'
cookbook 'logrotate'
cookbook 'ssh_known_hosts'
cookbook 'database'
cookbook 'ntp'
cookbook 'postgresql'
cookbook 'denyhosts'
cookbook 'hostname'
cookbook 'postfix'
