name             'uni'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures uni'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'postgresql'
# depends 'rbenv'
depends 'application'
# depends 'ruby_build'
depends 'poise-ruby'
depends 'poise-service'
depends 'poise-ruby-build'
depends 'application_ruby'
depends 'application_git'
# depends 'application_nginx'
depends 'iptables'
depends 'runit'
depends 'redisio'
depends 'nodejs'
depends 'nginx'
